### Problem Statement 

Implement dynamic pricing strategies for fitness classes based on demand, time, and location

- cult. fit (formerly cure. fit or Curefit) is a health and fitness company offering digital and offline experiences across fitness, nutrition, and mental well-being. With the aim to make fitness fun and easy, cult.
- Provided with the raw data, we need to built a predictive pricing strategy model for imporving the revenue of cult.fit

##### Import all the necessary libraries

In [60]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

##### Load the data

In [63]:
pwd

'C:\\Users\\DELL'

In [65]:
df1 = pd.read_csv('Classes April-May 2018.csv')

In [67]:
df1

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0
...,...,...,...,...,...,...,...
2172,NBL,Zumba Gold 12.45-1.45pm,01-May-18,12:45:00,60,47,1999.0
2173,NBL,Zumba Gold 12.45-1.45pm,08-May-18,12:45:00,60,42,1999.0
2174,NBL,Zumba Gold 12.45-1.45pm,15-May-18,12:45:00,60,38,1999.0
2175,NBL,Zumba Gold 12.45-1.45pm,22-May-18,12:45:00,60,39,1999.0
2176,NBL,Zumba Gold 12.45-1.45pm,29-May-18,12:45:00,60,41,1999.0

In [69]:
df2 = pd.read_csv('Classes June 2018.csv')

In [71]:
df2

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,BRP,20:20:20 9.30-10.30am,01-Jun-18,09:30:00,35,28,499
1,BRP,20:20:20 9.30-10.30am,08-Jun-18,09:30:00,35,35,499
2,BRP,20:20:20 9.30-10.30am,15-Jun-18,09:30:00,35,31,499
3,BRP,20:20:20 9.30-10.30am,22-Jun-18,09:30:00,35,32,499
4,BRP,20:20:20 9.30-10.30am,29-Jun-18,09:30:00,35,19,499
...,...,...,...,...,...,...,...
1107,TSC,Zumba 6.30-7.30pm,18-Jun-18,18:30:00,18,9,1299
1108,TSC,Zumba 6.30-7.30pm,25-Jun-18,18:30:00,18,9,1299
1109,TSC,Zumba - 6-7pm,07-Jun-18,18:00:00,50,16,1299
1110,TSC,Zumba - 6-7pm,14-Jun-18,18:00:00,50,13,1299
1111,TSC,Zumba - 6-7pm,21-Jun-18,18:00:00,50,12,1299

##### Concatenating the above 2 df's 

- df1 has data of april and may month
- df2 has the data of june month

##### Data holds the concatenated info of all the 3 month's togther

In [74]:
data = pd.concat([df1, df2],axis=0)

In [76]:
data

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0
...,...,...,...,...,...,...,...
1107,TSC,Zumba 6.30-7.30pm,18-Jun-18,18:30:00,18,9,1299.0
1108,TSC,Zumba 6.30-7.30pm,25-Jun-18,18:30:00,18,9,1299.0
1109,TSC,Zumba - 6-7pm,07-Jun-18,18:00:00,50,16,1299.0
1110,TSC,Zumba - 6-7pm,14-Jun-18,18:00:00,50,13,1299.0
1111,TSC,Zumba - 6-7pm,21-Jun-18,18:00:00,50,12,1299.0

##### Data Description

- ActivitySiteID
 
HXP:
High-Intensity Exercise Program: A type of workout regimen focusing on high-intensity training, often involving short bursts of intense activity followed by rest or low-intensity periods.

TSC:
Total Strength Conditioning: A comprehensive strength training program designed to enhance overall muscle strength and endurance.

NBL:
Nutrition-Based Lifestyle: A fitness approach emphasizing the importance of nutrition and dietary habits in achieving and maintaining fitness goals.
SBP:

Sports-Based Program: Fitness programs centered around sports activities, such as basketball, soccer, or other athletic pursuits, aimed at improving physical fitness through sports participation.
BRP:

Body Recomposition Program: A fitness program focused on changing body composition, specifically aiming to decrease body fat and increase muscle mass.

- ActivityDescription

The type of activity done based on the activity site

- BookingEndDateTime (Month / Day / Year)

The customer booking date as per the activity chosen

- BookingStartTime

The start time for the booking openings on the particular aligned day

- MaxBookees  

The maximum number of bookings opened for the batch

- Number Booked
  
Number of booking happened

- Price (INR)

Price based on the activity chosen by the customers

This column is the target for the predictive modelling which are building

#####  Data Understanding and Data cleaning

In [86]:
data.shape

(3289, 7)

- The data contains 3289 rows and 7 columns

In [89]:
data.columns

Index(['ActivitySiteID', 'ActivityDescription',
       'BookingEndDateTime (Month / Day / Year)', 'BookingStartTime',
       'MaxBookees', 'Number Booked', 'Price (INR)'],
      dtype='object')

- The data requires renaming of the columns names

In [92]:
data.rename(columns={'BookingEndDateTime (Month / Day / Year)':'BookingEndDateTime'},inplace=True)

In [94]:
data.rename(columns={'Number Booked':'Number_Booked'},inplace=True)
data.rename(columns={'Price (INR)':'Price'},inplace=True)

In [96]:
data.columns

Index(['ActivitySiteID', 'ActivityDescription', 'BookingEndDateTime',
       'BookingStartTime', 'MaxBookees', 'Number_Booked', 'Price'],
      dtype='object')

- the column names are in readable format

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3289 entries, 0 to 1111
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivitySiteID       3289 non-null   object
 1   ActivityDescription  3289 non-null   object
 2   BookingEndDateTime   3289 non-null   object
 3   BookingStartTime     3289 non-null   object
 4   MaxBookees           3289 non-null   int64
 5   Number_Booked        3289 non-null   int64
 6   Price                3271 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 205.6+ KB

- Since the target has null values we can drop them

In [102]:
data = data.loc[data['Price'].notna()]

In [104]:
data.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0

 BookingEndDateTime	and BookingStartTime
- The above columns are speaking about date and time but the default dtype is given as object
- We need to Standardize formats

In [107]:
data['BookingEndDateTime'] = pd.to_datetime(data['BookingEndDateTime'], format='%d-%b-%y')

In [109]:
data.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0

- Lets decompose the BookingEndDateTime into month year and day

In [111]:
data['BookingEndMonth'] = data['BookingEndDateTime'].dt.month

In [113]:
data['BookingEndDay'] = data['BookingEndDateTime'].dt.day

- From BookingStartTime we extracted hour and minute

In [116]:
data['BookingTime']=pd.to_datetime(data['BookingStartTime'],format="%H:%M:%S")

In [118]:
data['Booking_Start_Hour']=pd.to_datetime(data['BookingStartTime'],format="%H:%M:%S").dt.hour
data['Booking_Start_Min']=pd.to_datetime(data['BookingStartTime'],format="%H:%M:%S").dt.minute

In [120]:
data.drop('BookingTime',axis=1,inplace=True)

In [122]:
data.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,14,45
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,14,45
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,14,45
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,14,45
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,14,45

data.dtypes

- Checking for duplicates

In [764]:
data.duplicated().sum()

0

There are not duplicates in the data

- Cleaning the ActivityDescription columns

In [124]:
data1 = data.copy()

In [128]:
data1['Activity'] = data1['ActivityDescription'].str.rsplit(" ",n=1).str[0]

In [132]:
data1['Activity_Time'] = data1['ActivityDescription'].str.rsplit(" ",n=1).str[-1]

In [134]:
data1.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,2.45pm-3.45pm
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,2.45pm-3.45pm
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,2.45pm-3.45pm
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,2.45pm-3.45pm
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,2.45pm-3.45pm

In [161]:
data1.isnull().sum()

ActivitySiteID         0
ActivityDescription    0
BookingEndDateTime     0
BookingStartTime       0
MaxBookees             0
Number_Booked          0
Price                  0
BookingEndMonth        0
BookingEndDay          0
Booking_Start_Hour     0
Booking_Start_Min      0
Activity               0
Activity_Time          0
dtype: int64

In [154]:

from datetime import datetime, timedelta

def create_duration(time_str):
    start_time = datetime.strptime(time_str, '%H:%M:%S')
    end_time = start_time + timedelta(hours=1)
    return f"{start_time.strftime('%I:%M%p')} - {end_time.strftime('%I:%M%p')}"

In [163]:
data1['Activity_Time'] = np.where(data1.Activity_Time, data1['BookingStartTime'].apply(create_duration),data1.Activity_Time)

In [165]:
data1.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,02:45PM - 03:45PM
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,02:45PM - 03:45PM
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,02:45PM - 03:45PM
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,02:45PM - 03:45PM
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,02:45PM - 03:45PM

In [172]:
data1.drop(columns=['ActivityDescription'],axis=1,inplace=True)

In [194]:
data1.head()

,ActivitySiteID,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time
0,HXP,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,02:45PM - 03:45PM
1,HXP,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,02:45PM - 03:45PM
2,HXP,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,02:45PM - 03:45PM
3,HXP,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,02:45PM - 03:45PM
4,HXP,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,02:45PM - 03:45PM

In [176]:
# Function to calculate duration
def calculate_duration(time_range):
    time_range = time_range.replace(" ","")
    time_range = time_range.replace(".Am",'').replace('am',"").replace('AM',"").replace('am',"").replace('Am',"").replace('pm',"").replace('PM',"")
    time_range = time_range.replace('noon', '').replace("Noon","").replace(".",':')
    start_time_str, end_time_str = time_range.split('-')
    
    # Ensure times are in HH:MM format
    if ':' not in start_time_str:
        start_time_str += ':00'
    if ':' not in end_time_str:
        end_time_str += ':00'
    
    print(start_time_str, end_time_str)
    
    # Convert times to datetime objects
    start_time = datetime.strptime(start_time_str, '%H:%M')
    end_time = datetime.strptime(end_time_str, '%H:%M')
    
    if start_time.hour > end_time.hour:
        end_time = end_time.replace(hour=(end_time.hour + 12) % 24)
    
    # Calculate the duration in minutes
    duration = end_time - start_time
    duration_in_minutes = duration.total_seconds() / 60
    
    return duration_in_minutes

In [202]:
data1['Activity_Duration'] = data1['Activity_Time'].apply(calculate_duration)

02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:45 08:45
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
10:00 11:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
11:15 12:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
04:30 05:30
04:30 05:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
02:15 03:15
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
06:30 07:30
06:30 07:30
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
12:00 01:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:00 12:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
05:30 06:30
06:45 07:45
06:45 07:45
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
12:45 01:45
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
03:50 04:50
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:30 12:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
04:30 05:30
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
04:30 05:30
05:45 06:45
05:45 06:45
02:00 03:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
01:00 02:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
06:45 07:45
08:00 09:00
08:00 09:00
02:00 03:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
02:30 03:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
11:10 12:10
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:25 07:25
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
10:30 11:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
01:00 02:00
01:00 02:00
11:00 12:00
11:00 12:00
03:30 04:30
03:30 04:30
03:30 04:30
03:30 04:30
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
04:00 05:00
10:00 11:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
07:00 08:00
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
10:45 11:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:45 12:45
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:15 02:15
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
01:30 02:30
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
02:00 03:00
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
08:30 09:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
04:30 05:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
05:30 06:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:15 10:15
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
12:15 01:15
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
01:45 02:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
02:45 03:45
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
05:00 06:00
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
06:45 07:45
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:00 10:00
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
09:30 10:30
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
10:15 11:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
08:15 09:15
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
08:00 09:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
03:00 04:00
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
06:30 07:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
07:30 08:30
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
11:00 12:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
05:45 06:45
10:30 11:30
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
10:00 11:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:30 12:30
11:00 12:00
11:00 12:00
11:00 12:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:00 01:00
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
12:30 01:30
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
07:15 08:15
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00
06:00 07:00

In [204]:
data1.head()

,ActivitySiteID,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time,Activity_Duration
0,HXP,2018-04-08,14:45:00,25,12,499.0,4,8,14,45,20-20-20,02:45PM - 03:45PM,60.0
1,HXP,2018-04-15,14:45:00,25,15,499.0,4,15,14,45,20-20-20,02:45PM - 03:45PM,60.0
2,HXP,2018-04-22,14:45:00,25,14,499.0,4,22,14,45,20-20-20,02:45PM - 03:45PM,60.0
3,HXP,2018-04-29,14:45:00,25,9,499.0,4,29,14,45,20-20-20,02:45PM - 03:45PM,60.0
4,HXP,2018-05-06,14:45:00,25,7,499.0,5,6,14,45,20-20-20,02:45PM - 03:45PM,60.0

In [276]:
data1['Activity'] = data1['Activity'].str.replace(' ', '', regex=False)

In [278]:
data1['Activity'] = data1['Activity'].str.rsplit(" ",n=1).str[0]

In [288]:
data1['Activity'] = np.where(data1['Activity'] == '20:20:20', 
                                   data1['Activity'].str.replace(':', '-', regex=False), 
                                   data1['Activity'])

In [292]:
data1['Activity'] = np.where(data1['Activity'] == 'Aquababies/tots', 
                                   data1['Activity'].str.replace('Aquababies/tots', 'Aquatots&babies', regex=False), 
                                   data1['Activity'])

In [296]:
data1['Activity'] = np.where(data1['Activity'] == 'Aquatots/baby', 
                                   data1['Activity'].str.replace('Aquatots/baby', 'Aquatots&babies', regex=False), 
                                   data1['Activity'])

In [398]:

data1['Activity'] = np.where(data1['Activity'] == 'Aquafit', 
                                   data1['Activity'].str.replace('Aquafit', 'AquaFit', regex=False), 
                                   data1['Activity'])

In [302]:

data1['Activity'] = np.where(data1['Activity'] == 'BLT', 
                                   data1['Activity'].str.replace('BLT', 'BetterLivingTeam', regex=False), 
                                   data1['Activity'])

In [304]:

data1['Activity'] = np.where(data1['Activity'] == 'Body', 
                                   data1['Activity'].str.replace('Body', 'BodyAttack', regex=False), 
                                   data1['Activity'])

In [312]:

data1['Activity'] = np.where(data1['Activity'] == 'BodyBalan', 
                                   data1['Activity'].str.replace('BodyBalan', 'BodyBalance', regex=False), 
                                   data1['Activity'])

In [330]:
data1['Activity'] = np.where(data1['Activity'] == 'Better', 
                                   data1['Activity'].str.replace('Better', 'BetterLivingTeam', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Conditioning', 
                                   data1['Activity'].str.replace('Conditioning', 'BodyConditioning', regex=False), 
                                   data1['Activity'])

In [344]:
data1['Activity'] = np.where(data1['Activity'] == 'BodyConditioningd', 
                                   data1['Activity'].str.replace('BodyConditioningd', 'BodyConditioning', regex=False), 
                                   data1['Activity'])

In [354]:
data1['Activity'] = np.where(data1['Activity'] == 'BodyCondition10', 
                                   data1['Activity'].str.replace('BodyCondition10', 'BodyConditioning', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'BodyCond3.50pm-', 
                                   data1['Activity'].str.replace('BodyCond3.50pm-', 'BodyConditioning', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Bodycondition', 
                                   data1['Activity'].str.replace('Bodycondition', 'BodyConditioning', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Circuits7-7.45', 
                                   data1['Activity'].str.replace('Circuits7-7.45', 'Circuits', regex=False), 
                                   data1['Activity'])

In [406]:

data1['Activity'] = np.where(data1['Activity'] == 'Circuits8.00-9.00pm', 
                                   data1['Activity'].str.replace('Circuits8.00-9.00pm', 'Circuits', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Fusion5pm', 
                                   data1['Activity'].str.replace('Fusion5pm', 'Fusion', regex=False), 
                                   data1['Activity'])

data1['Activity'] = np.where(data1['Activity'] == 'GentleKeepFit2', 
                                   data1['Activity'].str.replace('GentleKeepFit2', 'GentleKeepFit', regex=False), 
                                   data1['Activity'])

data1['Activity'] = np.where(data1['Activity'] == 'Gentlekeepfit', 
                                   data1['Activity'].str.replace('Gentlekeepfit', 'GentleKeepFit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'H.I.T.T6pm-', 
                                   data1['Activity'].str.replace('H.I.T.T6pm-', 'H.I.T.T', regex=False), 
                                   data1['Activity'])

data1['Activity'] = np.where(data1['Activity'] == 'H.I.I.T.', 
                                   data1['Activity'].str.replace('H.I.I.T.', 'H.I.T.T', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'HattonAbcBox', 
                                   data1['Activity'].str.replace('HattonAbcBox', 'HattonABC', regex=False), 
                                   data1['Activity'])

data1['Activity'] = np.where(data1['Activity'] == 'HiitCircuit9.30-', 
                                   data1['Activity'].str.replace('HiitCircuit9.30-', 'HiitCircuit', regex=False), 
                                   data1['Activity'])

In [378]:

data1['Activity'] = np.where(data1['Activity'] == 'JuniorGym11-12' , 
                                   data1['Activity'].str.replace('JuniorGym11-12', 'JuniorGym', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'JuniorGym4-5pm' , 
                                   data1['Activity'].str.replace('JuniorGym4-5pm', 'JuniorGym', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'JuniorGym10-11am' , 
                                   data1['Activity'].str.replace('JuniorGym10-11am', 'JuniorGym', regex=False), 
                                   data1['Activity'])

In [414]:

data1['Activity'] = np.where(data1['Activity'] == 'LegBumTum' , 
                                   data1['Activity'].str.replace('LegBumTum', 'LegsBumsTums', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'LegsBumsTum' , 
                                   data1['Activity'].str.replace('LegsBumsTum', 'LegsBumsTums', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'LineDance' , 
                                   data1['Activity'].str.replace('LineDance', 'LineDancing', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'LineDancing2pm' , 
                                   data1['Activity'].str.replace('LineDancing2pm', 'LineDancing', regex=False), 
                                   data1['Activity'])

In [388]:
data1['Activity'] = np.where(data1['Activity'] == 'Pilates11.00-12.00' , 
                                   data1['Activity'].str.replace('Pilates11.00-12.00', 'Pilates', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Pilates14:45-' , 
                                   data1['Activity'].str.replace('Pilates14:45-', 'Pilates', regex=False), 
                                   data1['Activity'])

In [392]:
data1['Activity'] = np.where(data1['Activity'] == 'PureStretch11.00' , 
                                   data1['Activity'].str.replace('PureStretch11.00', 'PureStretch', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'RockRollDancing3-' , 
                                   data1['Activity'].str.replace('RockRollDancing3-', 'RockRollDancing', regex=False), 
                                   data1['Activity'])

In [416]:
data1['Activity'] = np.where(data1['Activity'] == 'JnrGymInd' , 
                                   data1['Activity'].str.replace('JnrGymInd', 'JunInduction', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Sh`Bam' , 
                                   data1['Activity'].str.replace('Sh`Bam', 'Sha`Bam', regex=False), 
                                   data1['Activity'])

In [420]:
data1['Activity'] = np.where(data1['Activity'] == 'Step' , 
                                   data1['Activity'].str.replace('Step', 'StepAerobics', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Step-' , 
                                   data1['Activity'].str.replace('Step-', 'StepZumba', regex=False), 
                                   data1['Activity'])

In [430]:
data1['Activity'] = np.where(data1['Activity'] == 'Strength&stretch1230-1330' , 
                                   data1['Activity'].str.replace('Strength&stretch1230-1330', 'Strength&stretch', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Stretch' , 
                                   data1['Activity'].str.replace('Stretch', 'Strength&stretch', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Stretch6pm' , 
                                   data1['Activity'].str.replace('Stretch6pm', 'Strength&stretch', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Stretch6pm' , 
                                   data1['Activity'].str.replace('Stretch6pm', 'Strength&stretch', regex=False), 
                                   data1['Activity'])

In [438]:
data1['Activity'] = np.where(data1['Activity'] == 'Stroke' , 
                                   data1['Activity'].str.replace('Stroke', 'Strokeskills', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Strokeskills6' , 
                                   data1['Activity'].str.replace('Strokeskills6', 'Strokeskills', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Strokeskills6pm-' , 
                                   data1['Activity'].str.replace('Strokeskills6pm-', 'Strokeskills', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Strokeskills7pm' , 
                                   data1['Activity'].str.replace('Strokeskills7pm', 'Strokeskills', regex=False), 
                                   data1['Activity'])

In [442]:
data1['Activity'] = np.where(data1['Activity'] == 'StudioCyc1.10-' , 
                                   data1['Activity'].str.replace('StudioCyc1.10-', 'StudioCyc', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'StudioCyc10.00' , 
                                   data1['Activity'].str.replace('StudioCyc10.00', 'StudioCyc', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'StudioCyc11.30-' , 
                                   data1['Activity'].str.replace('StudioCyc11.30-', 'StudioCyc', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'StudioCycling7.05' , 
                                   data1['Activity'].str.replace('StudioCycling7.05', 'StudioCyc', regex=False), 
                                   data1['Activity'])

In [450]:
data1['Activity'] = np.where(data1['Activity'] == 'Swim' , 
                                   data1['Activity'].str.replace('Swim', 'Swimfit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Swimfit7am-' , 
                                   data1['Activity'].str.replace('Swimfit7am-', 'Swimfit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Swimfit8pm-' , 
                                   data1['Activity'].str.replace('Swimfit8pm-', 'Swimfit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Swimfit6.30' , 
                                   data1['Activity'].str.replace('Swimfit6.30', 'Swimfit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Swimfit6.30am' , 
                                   data1['Activity'].str.replace('Swimfit6.30am', 'Swimfit', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Swimfit7pm-' , 
                                   data1['Activity'].str.replace('Swimfit7pm-', 'Swimfit', regex=False), 
                                   data1['Activity'])

In [458]:
data1['Activity'] = np.where(data1['Activity'] == 'Tai-Chi12' , 
                                   data1['Activity'].str.replace('Tai-Chi12', 'TaiChi', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Zumba6.00-' , 
                                   data1['Activity'].str.replace('Zumba6.00-', 'Zumba', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'BodyAttack9-10' , 
                                   data1['Activity'].str.replace('BodyAttack9-10', 'BodyAttack', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Strokeskills7pm' , 
                                   data1['Activity'].str.replace('Strokeskills7pm', 'Strokeskills', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'StudioCyc9.05' , 
                                   data1['Activity'].str.replace('StudioCyc9.05', 'StudioCyc', regex=False), 
                                   data1['Activity'])

In [472]:
data1['Activity'] = np.where(data1['Activity'] == '5.30-6.30pmBody' , 
                                   data1['Activity'].str.replace('5.30-6.30pmBody', 'BodyConditioning', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Combat' , 
                                   data1['Activity'].str.replace('Combat', 'BodyCombat', regex=False), 
                                   data1['Activity'])
data1['Activity'] = np.where(data1['Activity'] == 'Zumba-' , 
                                   data1['Activity'].str.replace('Zumba-', 'Zumba', regex=False), 
                                   data1['Activity'])

In [480]:
data1.sort_values('BookingEndDateTime',ignore_index=True,inplace=True)

In [482]:
data1

,ActivitySiteID,BookingEndDateTime,BookingStartTime,MaxBookees,Number_Booked,Price,BookingEndMonth,BookingEndDay,Booking_Start_Hour,Booking_Start_Min,Activity,Activity_Time,Activity_Duration
0,BRP,2018-04-01,09:00:00,35,29,1499.0,4,1,9,0,BodyCombat,09:00AM - 10:00AM,60.0
1,BRP,2018-04-01,10:00:00,20,15,1999.0,4,1,10,0,HattonABC,10:00AM - 11:00AM,60.0
2,HXP,2018-04-01,10:00:00,27,20,1999.0,4,1,10,0,StudioCyc,10:00AM - 11:00AM,60.0
3,HXP,2018-04-01,09:05:00,27,27,1999.0,4,1,9,5,StudioCyc,09:05AM - 10:05AM,60.0
4,TSC,2018-04-01,10:00:00,30,13,1299.0,4,1,10,0,BodyConditioning,10:00AM - 11:00AM,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,BRP,2018-06-30,09:00:00,35,21,1999.0,6,30,9,0,BodyAttack,09:00AM - 10:00AM,60.0
3267,TSC,2018-06-30,08:30:00,24,11,2999.0,6,30,8,30,BarrePilates,08:30AM - 09:30AM,60.0
3268,NBL,2018-06-30,12:00:00,60,9,2999.0,6,30,12,0,BarrePilates,12:00PM - 01:00PM,60.0
3269,SBP,2018-06-30,08:30:00,20,6,3999.0,6,30,8,30,MMACond,08:30AM - 09:30AM,60.0
3270,NBL,2018-06-30,10:00:00,60,9,1999.0,6,30,10,0,StepAerobics,10:00AM - 11:00AM,60.0

In [484]:
file_name = 'Data_Cult_fit_Lakshmi.xlsx'
 
# saving the excel
data1.to_excel(file_name)